# Generated by Django 2.0.3 on 2018-04-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=33)),
                ('content', models.TextField(null=True)),
                ('pub_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
